server:
  port: 8082

jwt:
  secret-key: h3w9qWUDH2K1S7owJK9rgrbQjF6jbRof0ep/6nBN+fA=

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      default-filters:
        - name: JwtAuthorizationFilter
          args:
            excludedPaths:
              - /api/auth/
              - /api/books
              - /api/members
              - /api/members/existsLoginId
              - /api/members/existsEmail
            adminPaths:
              - /api/admin/
            memberPaths:
              - /api/members/
      routes:
        - id: auth-service-route
          uri: http://localhost:8083
          predicates:
            - Path=/api/auth/**
        - id: book-service-route
          uri: http://localhost:8084
          predicates:
            - Path=/api/books/**
        - id: admin-book-service-route
          uri: http://localhost:8084
          predicates:
            - Path=/api/admin/**
        - id: member-service-route
          uri: http://localhost:8084
          predicates:
            - Path=/api/members/**
