server:
  port: 8082

jwt:
  secret-key: h3w9qWUDH2K1S7owJK9rgrbQjF6jbRof0ep/6nBN+fA=

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      default-filters:
        - name: JwtAuthorizationFilter
          args:
            excludedPaths:
              - path: /api/auth/
                methods: [ GET, POST ]
              - path: /api/books
              - path: /api/members/existsLoginId/
              - path: /api/members/existsEmail/
              - path: /api/payments
                #- /api/carts
              - path: /api/members
                methods: [ POST ]
            adminPaths:
              - path: /api/admin/
                methods: [ GET, POST, PUT, DELETE ]
            memberPaths:
              - path: /api/members
                methods: [ GET, PUT, DELETE ]
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service-route
          uri: http://localhost:8083
          predicates:
            - Path=/api/auth/**
        - id: book-service-route
          uri: lb://SHOP
          predicates:
            - Path=/api/books/**
        - id: cart-service-route
          uri: lb://SHOP
          predicates:
            - Path=/api/carts/**
        - id: admin-book-service-route
          uri: lb://SHOP
          predicates:
            - Path=/api/admin/**
        - id: member-service-route
          uri: lb://SHOP
          predicates:
            - Path=/api/members/**
        - id: payment-service-route
          uri: lb://SHOP
          predicates:
            - Path=/api/payments/**
    loadbalancer:
      health-check:
        enabled: true
        
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway
