server:
  port: 8082

jwt:
  secret-key: h3w9qWUDH2K1S7owJK9rgrbQjF6jbRof0ep/6nBN+fA=

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      default-filters:
        - name: JwtAuthorizationFilter
          args:
            excludedPaths:
              - /api/auth/login
              - /api/books/**
      routes:
        - id: auth-service-route
          uri: http://localhost:8083
          predicates:
            - Path=/api/auth/**
        - id: book
          uri: http://localhost:8084
          predicates:
            - Path=/api/books/**
