spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://133.186.241.167:3306/project_be7_heukbaekbook_dev?serverTimezone=UTC&characterEncoding=UTF-8
    username: be7_heukbaekbook
    password: 2t(o(baz7LQYzuws
    hikari:
      maximum-pool-size: 10
      register-mbeans: true
  rabbitmq:
    host: 133.186.241.167
    port: 5672
    username: admin
    password: nhnacademy123!
    virtual-host: vh1_dev
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 100
    hibernate:
      ddl-auto: none
  jmx:
    enabled: true

logging:
  level:
    com:
      zaxxer:
        hikari: DEBUG
