server:
  port: 8084

spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: none
    
aladin:
  api:
    key: ttbkdm89491015001
