aladin:
  api:
    key: ttbkdm89491015001

toss:
  secret-key: test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    status-page-url-path: /actuator/health
    health-check-url-path: /actuator/health

management:
  endpoints:
    web:
      exposure:
        include: health, info

spring:
  data:
    web:
      pageable:
        default-page-size: 25
