spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://133.186.241.167:3306/project_be7_heukbaekbook_dev?serverTimezone=UTC&characterEncoding=UTF-8
    username: be7_heukbaekbook
    password: 2t(o(baz7LQYzuws
    hikari:
      maximum-pool-size: 10
      register-mbeans: true
  data:
    redis:
      host: 133.186.241.167
      port: 6379
      password: '*N2vya7H@muDTwdNMR!'
      database: 102
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 100
    hibernate:
      ddl-auto: none

  elasticsearch:
    uris: http://115.94.72.197:9200
    username: elastic
    password: nhnacademy123!
    index:
      create-on-startup: true
    index-name: hbbook_dev

  jmx:
    enabled: true

logging:
  level:
    com:
      zaxxer:
        hikari: DEBUG
