feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

nhncloud:
  keymanager:
    appKey: 500rMJPT021TnyNl
    userAccessKeyId: j8vqyIPtFlYonUwbGB7e
    secretAccessKey: 3Ds4nuzS8pYtC3f8

redis:
  key: "8bf046001ecc4ee09792d17bfa05db73"

jwt:
  key: eec8381b385f45c3b990f3be8834eea4
  secret-key: ${secret.key}

spring:
  cloud:
    config:
      enabled: false
  main:
    allow-bean-definition-overriding: true
  session:
    store-type: redis # 세션 저장소를 지정합니다.
    redis:
      namespace: heukbaekbook:session # 세션을 저장하는 데 사용되는 키의 네임스페이스를 지정합니다.