spring:
  application:
    name: shop
  config:
    import: optional:configserver:http://localhost:9000

#nhn:
#  cloud:
#    tenant-id: fcb81f74e379456b8ca0e091d351a7af
#    api-user-id: fa38a82e97d646eb8c0bf90b5e3bae18
#    api-password: gmrqoransrh!!!

cloud:
  nhn:
    image-manager:
      url: https://api-image.nhncloudservice.com/image/v2.0/appkeys/rUN43QEwj1P6jThk
      app-key: rUN43QEwj1P6jThk
      secret-id: I1XLVufp
