feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

nhncloud:
  keymanager:
    appKey: 500rMJPT021TnyNl
    userAccessKeyId: j8vqyIPtFlYonUwbGB7e
    secretAccessKey: 3Ds4nuzS8pYtC3f8

redis:
  key: "8bf046001ecc4ee09792d17bfa05db73"


payco:
  client-id-key: 52a6943306d343c290333018f2096f9e
  client-secret-key: 4ed34dc0f902489884ed663554d0d9ed

spring:
  main:
    allow-bean-definition-overriding: true
  session:
    store-type: redis # 세션 저장소를 지정합니다.
    redis:
      namespace: heukbaekbook:session # 세션을 저장하는 데 사용되는 키의 네임스페이스를 지정합니다.
    timeout: 30m
  data:
    web:
      pageable:
        default-page-size: 25
  security:
    oauth2:
      client:
        registration:
          payco:
            client-id: ${client.id}
            client-secret: ${client.secret}
            client-authentication-method: post
            authorization-grant-type: authorization_code
            redirect-uri: "https://www.heukbaekbook.shop/login/oauth2/code/payco"
            scope: idNo, email, mobile, name
            client-name: PAYCO
        provider:
          payco:
            authorization-uri: https://id.payco.com/oauth2.0/authorize
            token-uri: https://id.payco.com/oauth2.0/token
            user-info-uri: https://apis-payco.krp.toastoven.net/payco/friends/find_member_v2.json
            user-name-attribute: idNo
