spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://133.186.241.167:3306/project_be7_heukbaekbook_dev?serverTimezone=UTC&characterEncoding=UTF-8
    username: be7_heukbaekbook
    password: 2t(o(baz7LQYzuws
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 1000
    hibernate:
      ddl-auto: none
  batch:
    jdbc:
      initialize-schema: always
